travis:
  secure:
    BINSTAR_TOKEN: TmFycU8KVRaLv5/nZyLQqQWaUJ80HbyBwBckzI0xFb6MPuWzQe1ofFiFT/QvNK7600obKu+n94rBzhOefcnjRJtB2jjGG+PMfe2MKWlBpYuvuL6zstXG7tITSO3MDUnff4s05UswZIGEZq8NhZSEbda+qGY7Igne9Y3Gu1iKL1bLSg/Es3y9bLa462NPC3UPe0+jjXE1fCf0HczETayz4Laj0EISu7ZpwD/XtLvTfk5CYzCwG4C3rTDc2oFp4h2e3AuUwV3mNG9Ga26pxyJ+lkNfzVAYtyh6D4F6LB1z73aYPxRTMK1waU/TbxlckEnQ2UiNN02pVTjf+SzejHusoA64ekvvkeQVS4NJmQthkmf/Xtr86q50MWptB77ZMGC5e59cmWCMsTjP7puwt/6nJxJvkC4WtwCpdhvKVQ2jtDVupC1sR46sCsHkRmhMVwzjYoTff/vT0exNTdym/bGGBmhaurTiIYUjmx0GCKbXy2BABOWcip8Wi4Z1ssitgvb3YQPUSXwqUPzxZb1enu9cUsC4YZiwM0XgOUe1FuNgYi83SkrmP3ZrAPBYdRlDdpgDYA6GisxcGSkdk6uBaVjZZXSD+BiimxmJQpeW2is4fj+ZnzKl6EdvDUcFOpRRjTxjU/Wi3aFNnQSk29ghmIUY+fSMR6ZPYvP1FfnK6RF+CpM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
